language: groovy
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
before_install:
- wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh
- ala_travis_grails_setup_env
script:
- grails clean && grails refresh-dependencies --non-interactive && grails test-app
  --non-interactive
- jdk_switcher use oraclejdk7
- grails prod maven-install --non-interactive && grails prod maven-deploy --repository=$MAVEN_REPO
  --non-interactive
env:
  global:
  - secure: X0gg6OP+b8yDYXjXDNOw2n8PiGqkerVRthlMIniYluAmTx+bHFqUC4cv3FzgqiD9oCwOSsucXQlPbur2NPkk8U5c6NVeNVtTVhtmG2Zzcvg7xCGhAcKVq3b+HVFR9QIcE6l2faxc9N42+2p3OdO5lDqboPjLSzp+OwiYpo364M/AuSxYF9XI1TVFt1tMbKazMrfDzGMOO2Fpy26jC1ICtHVWZ8Hk3A+K24WIGW5B2cRO1wkpMpUSo7MhLD+QwHiJSp78m5t1cEZ96OYweOxvA6NEC3u8+6AewpBiRStYjbqgNjx6Mg+zCFVE5u1f3z8hP6mekTxj8eulRAgANv6j1vrFKkSJcDgBYdxSsOvI4CZWFgfkGWDeXaEX4G5n20rdwUbR2RJgqQcZr1XHUqf2erayWrEKqP+jIETueiUiVe+5eyc9g90RFTuuG/OFWOm8k8BpkWP32c2Lt+xbU8LH+/QKwYlZxP1kLBnfXdGn5C0fU/tikiK+5NOHVe8/IWi27QoBlpYOaXT3BzfGqa0Zdig4Lqzzd4DKCwqA66uh0JZk4QTL2uHPIFEdFuduMwMsmxJvsHLKRTwWTfSK1G+BE8T4Hw4rwkw1beT5IBEr6hHAt5DRdZSQQaK9EXqyDdzhVdRU2Ls2LMO1MRO+0bvMwPfft0Jngc+vBwqJljy37zk=
  - secure: QcJJSNj0Q8zbJfMfzhUr2JBgh97nFr02kBa+fqI53zZJ5KWaGacuD+4j2Ht4y4tFwqF4oG/ankjRTNQBfhm7bj1UD6zaSdIidtnYKhcfgSluGfqGNT5kZBrwlYKdsUQ6Tv9qSqkaMqiBes9EE5Z9RKXIqY5Ar2cCAevMRWOJIqGAy/idGywjEd/TdBL1UsW4P/r2fD4F9Uzma35wKKMV1vUyg1+93o+dbozuBGjnx06YjR9C/z7lHegTlkP3st1hP3b6RCzw7Al9UBErwaWTqVK0r4+nxqBc/5gzVjlqKOAaFD8/XevXlQoYMcIsVxi7ySFhLFB9IO1VxzQC04T0CrY0YgnSwswm1GAY1QPVpylI9npzVsXhztCNCJOqXibkGe03KiSDePYOp4cb3STuCU5Ifyc9UgsvIwY5TWrF621hr6YG6syqGEdDtftPqj4lbOxCkc0a5j3Lh3MAUrTMLuer58AxhyGcmQFkiiqzF3fGLa5VJsrmyvboRQlGKZGqlsOG8ZjuWCaTHrQ0aWS26g85pCdAcwmIIUW21yA4zRf3hfIqCZ/JOHysP4KYnbLrMNgtV4bvMqAlROfg+UrjlbDo+M6aDTdQarUkHnVqJuwJDskd/oE2F9FV6rXuxa9cIiQErZNWv7FmeqwsiEynkVQP0zPT+CnIl3IwE2pXMkU=
