---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: au.org.ala.admin
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        build:
            date: '@info.app.build.date@'
endpoints:
    enabled: true
